double *grad_0_E0 = deriv_base + 0 * BLK_SZ;
double *grad_1_E0 = deriv_base + 1 * BLK_SZ;
double *grad_2_E0 = deriv_base + 2 * BLK_SZ;

double *grad_0_E1 = deriv_base + 3 * BLK_SZ;
double *grad_1_E1 = deriv_base + 4 * BLK_SZ;
double *grad_2_E1 = deriv_base + 5 * BLK_SZ;

double *grad_0_E2 = deriv_base + 6 * BLK_SZ;
double *grad_1_E2 = deriv_base + 7 * BLK_SZ;
double *grad_2_E2 = deriv_base + 8 * BLK_SZ;

double *grad_0_B0 = deriv_base + 9 * BLK_SZ;
double *grad_1_B0 = deriv_base + 10 * BLK_SZ;
double *grad_2_B0 = deriv_base + 11 * BLK_SZ;

double *grad_0_B1 = deriv_base + 12 * BLK_SZ;
double *grad_1_B1 = deriv_base + 13 * BLK_SZ;
double *grad_2_B1 = deriv_base + 14 * BLK_SZ;

double *grad_0_B2 = deriv_base + 15 * BLK_SZ;
double *grad_1_B2 = deriv_base + 16 * BLK_SZ;
double *grad_2_B2 = deriv_base + 17 * BLK_SZ;

double *grad_0_Phi = deriv_base + 18 * BLK_SZ;
double *grad_1_Phi = deriv_base + 19 * BLK_SZ;
double *grad_2_Phi = deriv_base + 20 * BLK_SZ;

double *grad_0_Psi = deriv_base + 21 * BLK_SZ;
double *grad_1_Psi = deriv_base + 22 * BLK_SZ;
double *grad_2_Psi = deriv_base + 23 * BLK_SZ;
